# CLI command -> API operations ("METHOD /path")
I='{identifier}'
CRUD=lambda base,c=None,l=True,u=True,d=True: None
M = {
 'label-create':['POST /labels'],'label-delete':['DELETE /labels/'+I],'label-list':['GET /labels','GET /labels/'+I],'label-update':['PUT /labels/'+I],
 'objective-create':['POST /objectives'],'objective-delete':['DELETE /objectives/'+I],'objective-export':['POST /objectives/export'],
 'objective-import':['POST /objectives/import'],'objective-list':['GET /objectives','GET /objectives/'+I],'objective-update':['PUT /objectives/'+I],
 'privileged-delete':['DELETE /files/worm/{share-identifier}/{path}'],
 'share-clone-create':['POST /share-snapshots/clone-create/{share-identifier}'],
 'share-create':['POST /shares'],'share-delete':['DELETE /shares/'+I],'share-list':['GET /shares','GET /shares/'+I],
 'share-mount':['GET /shares/{identifier}/mount-details','GET /shares/mount-details'],'share-move':['POST /shares/{identifier}/move/{path}'],
 'share-objective-add':['POST /shares/{identifier}/objective-set','POST /shares/{identifier}/objective-update'],
 'share-objective-list':['GET /shares/{identifier}/objective-list'],'share-objective-remove':['POST /shares/{identifier}/objective-unset'],
 'share-objective-reset':['POST /shares/{identifier}/objective-reset'],
 'share-snapshot-create':['POST /share-snapshots/snapshot-create/{share-identifier}','POST /share-snapshots'],
 'share-snapshot-delete':['POST /share-snapshots/snapshot-delete/{share-identifier}/{snapshot-name}'],
 'share-snapshot-list':['GET /share-snapshots/snapshot-list/{share-identifier}'],
 'share-snapshot-restore':['POST /share-snapshots/snapshot-restore/{share-identifier}/{snapshot-name}','POST /share-snapshots/snapshot-restore-files/{share-identifier}/{snapshot-name}'],
 'share-snapshot-schedule-list':['GET /share-snapshots'],'share-snapshot-update':['PUT /share-snapshots/'+I,'DELETE /share-snapshots/'+I],
 'share-undelete':['POST /shares/{identifier}/undelete'],'share-update':['PUT /shares/'+I],
 'ad-discover':['GET /ad/discover/{domain}'],'ad-config':['GET /ad','GET /ad/'+I,'PUT /ad/'+I,'POST /ad/flush_cache'],
 'domain-idmap-add':['POST /domain-idmaps'],'domain-idmap-delete':['DELETE /domain-idmaps/'+I],'domain-idmap-list':['GET /domain-idmaps','GET /domain-idmaps/'+I],
 'domain-idmap-reload':['POST /domain-idmaps/reload'],
 'smb-config':['PUT /ad/'+I,'GET /smbautohomes','POST /smbautohomes','PUT /smbautohomes/'+I,'DELETE /smbautohomes/'+I,'DELETE /smbautohomes/default','DELETE /smbautohomes/username/{username}','GET /smbautohomes/username/{username}'],
 'cert-add':['POST /pki-certificates'],'cert-ca-list':['GET /pki-certificate-authorities','GET /pki-certificate-authorities/system','GET /pki-certificate-authorities/{uuid}'],
 'cert-csr-sign':['POST /pki-certificates/sign-csr'],'cert-list':['GET /pki-certificates','GET /pki-certificates/{uuid}','GET /pki-managed-certificates','GET /pki-managed-certificates/{uuid}'],
 'cert-remove':['DELETE /pki-certificates/'+I],
 'cluster-config':['PUT /cntl/'+I,'GET /cntl','GET /cntl/'+I],
 'dns-config':['GET /dnss','GET /dnss/'+I,'PUT /dnss/'+I],
 'dp-update':['PUT /data-portals/'+I,'GET /data-portals'],
 'email-config':['GET /mail/smtp','GET /mail/smtp/'+I,'POST /mail/smtp','PUT /mail/smtp/'+I,'DELETE /mail/smtp/'+I,'POST /mail/smtp/test/{email}'],
 'event-list':['GET /events','GET /events/'+I,'GET /events/summary'],'event-update':['PUT /events/'+I,'PUT /events/clear'],
 'heartbeat-list':['GET /heartbeat'],'heartbeat-send':['POST /heartbeat/send/'+I],'heartbeat-update':['PUT /heartbeat/'+I],
 'identity-group-mapping-create':['POST /identity-group-mappings'],'identity-group-mapping-delete':['DELETE /identity-group-mappings/'+I],
 'identity-group-mapping-list':['GET /identity-group-mappings','GET /identity-group-mappings/'+I],'identity-group-mapping-update':['PUT /identity-group-mappings/'+I],
 'idp-add':['POST /idp'],'idp-list':['GET /idp','GET /idp/'+I],'idp-remove':['DELETE /idp/'+I],'idp-update':['PUT /idp/'+I],
 'kms-add':['POST /kmses'],'kms-list':['GET /kmses','GET /kmses/'+I],'kms-remove':['DELETE /kmses/'+I],'kms-update':['PUT /kmses/'+I],
 'local-site-config':['GET /sites/local','PUT /sites/'+I],
 'license-add':['POST /licenses'],'license-list':['GET /licenses','GET /licenses/{activation-id}'],
 'license-offline-add':['POST /licenses/offline-add-request-download','POST /licenses/offline-add-request-export','POST /licenses/offline-add-response-import/{activation-id}/{import-uri}','POST /licenses/offline-add-response-upload/{activation-id}'],
 'license-offline-cancel':['POST /licenses/offline-cancel-pending/{activation-id}'],
 'license-offline-remove':['POST /licenses/offline-remove-request-download/{activation-id}','POST /licenses/offline-remove-request-export/{activation-id}','POST /licenses/offline-remove-response-import/{activation-id}/{import-uri}','POST /licenses/offline-remove-response-upload/{activation-id}'],
 'license-offline-update':['POST /licenses/offline-update-request-download','POST /licenses/offline-update-request-export','POST /licenses/offline-update-response-import/{activation-id}/{import-uri}','POST /licenses/offline-update-response-upload/{activation-id}'],
 'license-remove':['DELETE /licenses/{activation-id}'],'license-update':['PUT /licenses/{activation-id}'],
 'metric-list':['GET /metrics','GET /metrics/native'],
 'name-service-config':['GET /name-services','POST /name-services','GET /name-services/'+I,'PUT /name-services/'+I,'DELETE /name-services/'+I,'PUT /name-services/reorder','POST /name-services/connectionTest','GET /name-services/resolveUser','GET /name-services/resolveGroup','GET /name-services/resolveUserGroups','GET /ldaps','POST /ldaps','PUT /ldaps/'+I,'DELETE /ldaps/'+I],
 'nis-config':['GET /nis','GET /nis/'+I,'PUT /nis/'+I],
 'notification-rule-create':['POST /notification-rules'],'notification-rule-list':['GET /notification-rules','GET /notification-rules/'+I],
 'notification-rule-remove':['DELETE /notification-rules/'+I],'notification-rule-update':['PUT /notification-rules/'+I],
 'ntp-config':['GET /ntps','GET /ntps/'+I,'PUT /ntps/'+I],
 'support-bundle':['POST /pd-support'],
 'remote-site-add':['POST /sites'],'remote-site-discover':['GET /sites/discover/{address}'],'remote-site-list':['GET /sites','GET /sites/'+I],
 'remote-site-remove':['DELETE /sites/'+I],'remote-site-update':['PUT /sites/'+I],
 'schedule-create':['POST /schedules'],'schedule-delete':['DELETE /schedules/'+I],'schedule-list':['GET /schedules','GET /schedules/'+I],'schedule-update':['PUT /schedules/'+I],
 'snmp-config':['GET /snmp','GET /snmp/'+I,'PUT /snmp/'+I,'POST /snmp/trap-test'],
 'software-apply':['POST /sw-update/apply/{version}','POST /sw-update/apply/{version}/system'],'software-list':['GET /versions/available'],
 'software-package-delete':['POST /versions/delete'],'software-update-cancel':['POST /sw-update/{identifier}/cancel'],
 'software-update-status':['GET /sw-update','GET /sw-update/'+I],'software-upload':['POST /versions/upload','POST /versions/upload/{package-location}'],
 'syslog-config':['GET /syslog','GET /syslog/'+I,'PUT /syslog/'+I],
 'system-backup-config':['GET /backup','POST /backup','PUT /backup/'+I,'DELETE /backup/'+I,'POST /backup/backup-create/{volume-ip}/{export-path}'],
 'system-backup-list':['GET /backup/backup-list/{volume-ip}/{export-path}'],
 'system-backup-restore':['POST /backup/backup-restore/{volume-ip}/{export-path}','POST /backup/backup-restore/{volume-ip}/{export-path}/{backup-name}'],
 'system-shutdown':['POST /cntl/shutdown'],'system-view':['GET /system-info','GET /system/health','GET /system/counts','GET /cntl/state'],
 'task-cancel':['POST /tasks/cancel-active'],'task-list':['GET /tasks','GET /tasks/'+I],'task-resume':['PUT /tasks/{taskId}'],
 'builtin-group-user-add':['POST /users/builtin/user-add/{groupname}/{username}'],'builtin-group-user-list':['GET /users/builtin/user-list/{groupname}'],
 'builtin-group-user-remove':['POST /users/builtin/user-remove/{groupname}/{username}'],
 'login-policy-config':['GET /login-policy','POST /login-policy','GET /login-policy/'+I,'PUT /login-policy/'+I],
 'role-create':['POST /roles'],'role-delete':['DELETE /roles/'+I],'role-list':['GET /roles','GET /roles/'+I],'role-update':['PUT /roles/'+I],
 'user-create':['POST /users'],'user-delete':['DELETE /users/'+I],'user-import':['POST /users/import','POST /users/import/{path}'],
 'user-list':['GET /users','GET /users/'+I],'user-password-update':['PUT /users/{identifier}/password','POST /users/{identifier}/reset-password'],'user-update':['PUT /users/'+I],
 'mdsi-add':['POST /mdsis'],'mdsi-list':['GET /mdsis','GET /mdsis/'+I],'mdsi-remove':['DELETE /mdsis/'+I],
 'drive-list':['GET /disk-drives','GET /disk-drives/'+I],
 'logical-volume-create':['POST /logical-volumes'],'logical-volume-delete':['DELETE /logical-volumes/'+I],
 'logical-volume-discover':['GET /logical-volumes/{identifier}/discover'],'logical-volume-list':['GET /logical-volumes','GET /logical-volumes/'+I],
 'node-add':['POST /nodes'],'node-list':['GET /nodes','GET /nodes/'+I,'GET /nodes/unauthenticated'],'node-mode-change':['POST /nodes/{identifier}/set-mode/{mode}'],
 'node-refresh':['POST /nodes/{identifier}/refresh'],'node-remove':['DELETE /nodes/'+I],'node-storage-repair':['POST /pd-node-cntl/repair'],'node-update':['PUT /nodes/'+I],
 'nvmeof-config':['GET /nvmeof-enclosures','POST /nvmeof-enclosures','PUT /nvmeof-enclosures/discover','GET /nvmeof-enclosures/'+I,'PUT /nvmeof-enclosures/'+I,'DELETE /nvmeof-enclosures/'+I],
 'object-logical-volume-discover':['GET /object-store-logical-volumes/{identifier}/discover','GET /object-store-logical-volumes/'+I],
 'object-storage-add':['POST /nodes'],'object-storage-update':['PUT /nodes/'+I],
 'object-volume-add':['POST /object-storage-volumes'],'object-volume-decommission':['POST /object-storage-volumes/{identifier}/decommission'],
 'object-volume-decommission-cancel':['POST /tasks/cancel-active'],'object-volume-fail':['PUT /object-storage-volumes/'+I],
 'object-volume-gc-start':['POST /object-storage-volumes/{identifier}/garbage-collect'],'object-volume-gc-stop':['DELETE /object-storage-volumes/{identifier}/garbage-collect'],
 'object-volume-list':['GET /object-storage-volumes','GET /object-storage-volumes/'+I],
 'object-volume-remove':['DELETE /object-storage-volumes/'+I,'POST /object-storage-volumes/{identifier}/replace'],
 'object-volume-reservation-delete':['PUT /object-storage-volumes/{identifier}/remote-reservation/{site-identifier}'],
 'object-volume-update':['PUT /object-storage-volumes/'+I],
 's3-server-bucket-create':['POST /s3server/{identifier}/bucket'],'s3-server-bucket-remove':['DELETE /s3server/{identifier}/bucket'],
 's3-server-create':['POST /s3server'],'s3-server-delete':['DELETE /s3server/'+I],'s3-server-list':['GET /s3server','GET /s3server/'+I,'GET /s3server/{identifier}/listBuckets'],
 's3-server-update':['PUT /s3server/'+I],'s3-server-user-add':['POST /s3server/{identifier}/user'],'s3-server-user-remove':['DELETE /s3server/{identifier}/user'],
 'volume-add':['POST /storage-volumes'],'volume-assimilation':['POST /storage-volumes/{identifier}/assimilation'],'volume-assimilation-cancel':['POST /tasks/cancel-active'],
 'volume-decommission':['POST /storage-volumes/{identifier}/decommission'],'volume-decommission-cancel':['POST /tasks/cancel-active'],
 'volume-fail':['PUT /storage-volumes/'+I],
 'volume-group-create':['POST /volume-groups'],'volume-group-delete':['DELETE /volume-groups/'+I],'volume-group-list':['GET /volume-groups','GET /volume-groups/'+I],
 'volume-group-update':['PUT /volume-groups/'+I],'volume-list':['GET /storage-volumes','GET /storage-volumes/'+I,'GET /base-storage-volumes','GET /base-storage-volumes/'+I],
 'volume-remove':['DELETE /storage-volumes/'+I,'POST /storage-volumes/{identifier}/replace'],'volume-update':['PUT /storage-volumes/'+I],
 'file-snapshot-create':['POST /file-snapshots/create','POST /file-snapshots'],'file-snapshot-delete':['POST /file-snapshots/delete','DELETE /file-snapshots/'+I],
 'file-snapshot-list':['GET /file-snapshots/list'],'file-snapshot-restore':['POST /file-snapshots/restore','POST /file-snapshots/{file-source}/{file-destination}'],
 'file-snapshot-schedule-list':['GET /file-snapshots','GET /file-snapshots/'+I],'file-snapshot-update':['PUT /file-snapshots/'+I],
 'snapshot-retention-create':['POST /snapshot-retentions'],'snapshot-retention-delete':['DELETE /snapshot-retentions/'+I],
 'snapshot-retention-list':['GET /snapshot-retentions','GET /snapshot-retentions/'+I],'snapshot-retention-update':['PUT /snapshot-retentions/'+I],
 'floating-ip-add':['PUT /cntl/'+I],'floating-ip-remove':['PUT /cntl/'+I],
 'gateway-update':['PUT /gateways/'+I],'gateway-list':['GET /gateways','GET /gateways/{node}'],
 'interface-create':['POST /network-interfaces/'+I],'interface-delete':['DELETE /network-interfaces/'+I],
 'interface-list':['GET /network-interfaces','GET /network-interfaces/'+I],'interface-update':['PUT /network-interfaces/'+I],
 'static-route-add':['POST /static-routes'],'static-route-delete':['DELETE /static-routes/'+I],'static-route-list':['GET /static-routes'],
 'subnet-gateway-add':['POST /subnet-gateways'],'subnet-gateway-delete':['DELETE /subnet-gateways/'+I],'subnet-gateway-list':['GET /subnet-gateways'],
 'gfs-participant-add':['POST /share-participants'],'gfs-participant-disable':['PUT /share-participants/change-admin-state'],
 'gfs-participant-enable':['PUT /share-participants/change-admin-state'],'gfs-participant-list':['GET /share-participants','GET /share-participants/'+I],
 'gfs-participant-remove':['DELETE /share-participants/'+I,'DELETE /share-participants/{share-identifier}/{site-identifier}'],
 'share-offline':['PUT /shares/'+I],'share-online':['PUT /shares/'+I],'share-unmount':['GET /shares/{identifier}/mount-details'],
 'volume-set-available':['PUT /storage-volumes/'+I],'volume-set-unavailable':['PUT /storage-volumes/'+I],
 'object-volume-set-available':['PUT /object-storage-volumes/'+I],'object-volume-set-unavailable':['PUT /object-storage-volumes/'+I],
 'volume-remove-cancel':['POST /tasks/cancel-active'],'object-volume-remove-cancel':['POST /tasks/cancel-active'],
}

# Commands that exist in the CLI but are not documented in the Command Line Reference (confirmed by users)
EXTRA_COMMANDS = {
 'antivirus-add':    {'chapter': 'System', 'summary': 'Add an antivirus service', 'ops': ['POST /antivirus']},
 'antivirus-list':   {'chapter': 'System', 'summary': 'List antivirus services', 'ops': ['GET /antivirus', 'GET /antivirus/'+I]},
 'antivirus-remove': {'chapter': 'System', 'summary': 'Remove an antivirus service', 'ops': ['DELETE /antivirus/'+I]},
 'antivirus-update': {'chapter': 'System', 'summary': 'Update an antivirus service', 'ops': ['PUT /antivirus/'+I]},
 'preview-no-upload-object-volume-add': {'chapter': 'Storage and Volumes', 'summary': 'Add a zero durability object storage volume (technology preview)', 'ops': ['POST /object-storage-volumes']},
 # processor-add/-list/-update/-remove exist in the CLI help but have no matching endpoint in this API spec
}
for _k, _v in EXTRA_COMMANDS.items(): M[_k] = _v['ops']
